### ISSUE TITLE
Transform looks for all <code>, not <pre><code>

### ISSUE THREAD

**Issue by MegaJ** [fortes/metalsmith-code-highlight#13]
My main usecase is that I have `<code>` tags that I don't want marked up by this plugin, but I still want the highlight for other code blocks.

I was writing some `<code>` elements that I wanted inline. The relevant DOM structure is  
```<li>blah blah text <code>$ cowsay </code> more text </li>```, which will still be highlighted, and the `code` gets marked up because the the sourcecode looks up all `<code>`. If I have subsequent `<code>` elements in that `<li>`, nothing happens to them; they won't have the `hljs` class (not sure why).

[highlight.js](https://github.com/isagalaev/highlight.js#getting-started) says that it finds `<pre><code>` tags.

Why does the sourcecode select all `code` instead of `'pre > code'`?

**Comment by fortes** [comment]
@MegaJ Yup, currently the plugin looks for all `code` elements ( https://github.com/fortes/metalsmith-code-highlight/blob/master/transform.js#L7 ). Wouldn't be too difficult to make this a parameter that we are able to pass into the plugin.

Your other option (and what I do on my site) is to pass in `languages: []` to the plugin, which will turn off auto-detection of the language, and effectively disable the highlighting (this assumes that you are specifying language in your code blocks, which works like GitHub markdown).
![screenshot 2018-01-29 at 09 38 59](https://user-images.githubusercontent.com/5181/35515854-3f1ee028-04d8-11e8-8544-a23d161da7ba.png)

**Comment by MegaJ** [comment]
Thanks for maintaining this repo!

I actually have the `languages: []` set, and it still marks up my example DOM structure. This is in the latest version, 1.0.3. I think there's a distinction between highlighting and the metalsmith-code-highlight adding class markup to my html. I want the class markup to not appear.

The empty language setting is useful. I write html and write the class into the element like this: `<pre><code class=lang-java>` Without the `lang-java` there isn't syntax highlighting, but the `hljs` class is still added. This class then styles the element. This is expected because it's still `pre > code`. 

The problem I have is when I just have `li > code` or `p > code`. The code is still marked up and styled by the `hljs` class, but there isn't "hightlighting" in the sense that I get colors. I mostly care about this because highlight makes `.hljs` elements `display: block` (and of course this depends on the theme, though I think most make it a block). Sure, I can override this with my own CSS, but that's more CSS architecture, and more markup in a plain `<code>` element, that should be by default, `display: inline`.

I modified the query selector to `pre > code` and it worked the way I wanted to. I am in favor of a parameter being added, as I don't want to maintain my own version of metalsmith-code-highlight.

If a parameter is being added, should we just allow the user to specify their own query selector? highlight.js has no setting to change selectors that I'm aware of, so the user should probably only put in some combination of `pre` and/or `code` with whatever combinators.

**Comment by fortes** [comment]
> If a parameter is being added, should we just allow the user to specify their own query selector? highlight.js has no setting to change selectors that I'm aware of, so the user should probably only put in some combination of pre and/or code with whatever combinators.

My first attempt would be to have a parameter with a default value of `code`, then people can override and set whatever they want (`pre > code` in your case)

If you have time, feel free to send a PR! :)

**Comment by MegaJ** [comment]
@fortes Give me a little time. I think I have repetitive strain injury from the keyboard.

**Comment by MegaJ** [comment]
Yay, merged and happy.
